apiVersion: v1
kind: Pod
metadata:
  name: test-docker
  labels:
    component: ci
spec:
  # Use service account that can deploy to all namespaces
  # serviceAccountName: jenkins
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
  containers:
  - name: docker
    image: docker:dind
    securityContext:
      privileged: true
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
